# Generated by Django 4.2.7 on 2023-11-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('o', 'معمولی'), ('v', 'vip')], max_length=1)),
                ('bed_count', models.IntegerField()),
                ('features', models.TextField()),
                ('price_one_night', models.IntegerField()),
                ('has_Resev', models.BooleanField(default=False)),
                ('code', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
