# Generated by Django 4.2.7 on 2023-12-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_type_roomreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservation',
            name='been_paid',
            field=models.IntegerField(default=0),
        ),
    ]
