# Generated by Django 4.2.7 on 2023-12-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomreservation_been_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(default='rooms/image.jpg', upload_to='rooms/'),
        ),
    ]
