# Generated by Django 4.2.7 on 2023-12-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roomtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
