# Generated by Django 4.2.7 on 2023-12-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_roomtype_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomreservation',
            name='check_out',
        ),
    ]
