# Generated by Django 4.2.7 on 2023-12-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_roomreservation_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='check_in',
            field=models.DateField(),
        ),
    ]
