# Generated by Django 4.2.7 on 2023-12-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_roomreservation_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
