# Generated by Django 4.2.7 on 2024-01-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_roomreservation_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='features',
            new_name='description',
        ),
    ]
