# Generated by Django 4.2.7 on 2023-11-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('u', 'کاربر عادی'), ('m', 'مدیر هتل'), ('d', 'معاون هتل'), ('a', 'پذیرش هتل'), ('r', 'مدیر رستوران')], default='u', max_length=1),
        ),
    ]
