# Generated by Django 4.2.7 on 2023-12-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_can_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='data/users/image.jpg', upload_to='data/users/'),
        ),
    ]
