# Generated by Django 4.2.7 on 2023-12-19 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_comment_roomcomment_foodcomment'),
        ('accounts', '0007_payments'),
    ]

    operations = [
    ]
