# Generated by Django 4.2.7 on 2024-01-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_comment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
