# Generated by Django 4.2.7 on 2023-11-30 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('meal', models.CharField(choices=[('m', 'صبحانه'), ('d', 'ناهار'), ('n', 'شام')], max_length=1)),
                ('type', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('reserve', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
