# Generated by Django 4.2.7 on 2023-12-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_foodreservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default='foods/image.jpg', upload_to='foods/'),
        ),
    ]
