# Generated by Django 4.2.7 on 2023-12-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreservation',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
    ]
