# Generated by Django 4.2.7 on 2023-12-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_foodreservation_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreservation',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
