# Generated by Django 4.2.7 on 2024-01-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_rename_type_food_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreservation',
            name='meal',
            field=models.CharField(choices=[('d', 'ناهار'), ('n', 'شام')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
