# Generated by Django 4.2.7 on 2024-01-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_foodreservation_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='meal',
        ),
    ]
