# Generated by Django 4.2.7 on 2024-01-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_remove_food_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreservation',
            name='place',
            field=models.CharField(choices=[('r', 'رستوران'), ('a', 'اتاق')], default='r', max_length=1),
        ),
    ]
